apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32000   # Access Jenkins UI
    - name: jnlp
      port: 50000
      targetPort: 50000
      nodePort: 32001   # Agent connectivity
